name: nebuchadnezzar
base: core24
version: git
summary: Matrix Client
description: |
  Matrix Client
grade: stable
confinement: strict
contact: https://github.com/ubuntu-flutter-community/nebuchadnezzar/issues
issues: https://github.com/ubuntu-flutter-community/nebuchadnezzar/issues
website: https://github.com/ubuntu-flutter-community/nebuchadnezzar
license: GPL-3.0+
icon: assets/nebuchadnezzar.png

platforms:
  amd64:
  arm64:

apps:
  nebuchadnezzar:
    command: bin/nebuchadnezzar
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-status

parts:
  flutter-git:
    plugin: nil
    source: .
    override-build: |
      bash $CRAFT_PART_SRC/scripts/install-fvm.sh
      fvm install
      fvm flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ""

  nebuchadnezzar:
    after: [flutter-git]
    source: .
    plugin: nil
    override-build: |
      set -eux
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      craftctl default
      fvm install
      fvm dart pub get
      fvm flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - libssl-dev
      - libpciaccess-dev

  deps:
    plugin: nil
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - libpciaccess0

    prime:
      - usr/lib/*/*.so*
